// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Template1.EntityFrameworkCore;

namespace Template1.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(DemoDotNetCoreDbContext))]
    [Migration("20181101085009_Initinal")]
    partial class Initinal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.NETCore.Demo.Entity.DemoDotNetCore.MicroserviceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AzureResourceType")
                        .HasColumnName("AzureResourceType")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CodingLanguage")
                        .HasColumnName("CodingLanguage")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Dependencies")
                        .HasColumnName("Dependencies")
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Developers")
                        .HasColumnName("Developers")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductOwner")
                        .HasColumnName("ProductOwner")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RepositoryName")
                        .HasColumnName("RepositoryName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResponsibleTeam")
                        .HasColumnName("ResponsibleTeam")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ScrumMaster")
                        .HasColumnName("ScrumMaster")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ServiceAliasName")
                        .HasColumnName("ServiceAliasName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ServiceCategory")
                        .HasColumnName("ServiceCategory")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ServiceChineseName")
                        .HasColumnName("ServiceChineseName")
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasColumnName("ServiceCode")
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ServiceConfluenceUrl")
                        .HasColumnName("ServiceConfluenceUrl")
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortNo")
                        .HasColumnName("SortNo");

                    b.Property<string>("TechniqueOwner")
                        .HasColumnName("TechniqueOwner")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Microservice", "dbo");
                });

            modelBuilder.Entity("WebApi.NETCore.Demo.Entity.DemoDotNetCore.ServiceDefinitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasColumnName("ServiceCode")
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("SortNo")
                        .HasColumnName("SortNo");

                    b.HasKey("Id");

                    b.ToTable("ServiceDefinition", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
